### ISSUE TITLE
Option to process values in certain HTML attributes

### ISSUE THREAD

**Issue by gavinmcfarland** [Raiyee/gulp-htmlpostcss#1]
Would it be possible to process certain HTML attributes that contain style related data? Specifically things like `width`?

The use case is when you want to process the data inside the attribute using a PostCSS plugin.

For example if I want to use a custom grid unit instead of pixels.

```
<div width="50gu">...</div>
```

Which would output

```
<div width="200px">...</div>
```

**Comment by JounQin** [comment]
https://github.com/Rebelmail/html-postcss/blob/master/lib/html-postcss.js#L15-L30
